
kind: Pod
apiVersion: v1
metadata:
  name: test-pod2
spec:
  containers:
  - name: test-pod2
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS-minio && exit 0 || exit 1"
    volumeMounts:
      - name: minio-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: minio-pvc
      persistentVolumeClaim:
        claimName: pv-claim