apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ng-deploy
  name: ng-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ng-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ng-app
        version: 1.1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
