apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ddeploy
  name: ddeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ddeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ddeploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
