---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'demko'
spec:
  destination:
    name: ''
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/demko
    repoURL: 'https://github.com/ebi-droid/Kubernety.git'
    targetRevision: HEAD
  project: 'default'
  syncPolicy:
    automated:
      selfHeal: false
      prune: false