apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
  storageClassName: minio-local-storage
  #selector:
   # matchLabels:
   #   release: "stable"
    #matchExpressions:
     # - {key: environment, operator: In, values: [dev]}
