apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: L2Advertisement
  metadata:
    name: metallb-pool
    namespace: metallb-system
  spec:
    ipAddressPools:
    - metallb-pool
kind: List
metadata:
  resourceVersion: ""
